#!/bin/sh

directory=${PWD##*/}
if [ $directory != "euler-problems" ]; then
   echo "You must be in the euler-problems directory to execute clean."
   exit 1
fi

echo "Removing all .beam files..."
find . -name \*.beam | xargs rm

echo "Removing all emacs backup files..."
find . -name \*~ | xargs rm

echo "Removing all erl_crash.dump files..."
find . -name erl_crash.dump | xargs rm
